name: Cost Optimization CI

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Updated to latest version
    
    - name: Set up Java 8
      uses: actions/setup-java@v3  # Updated to latest version
      with:
        distribution: 'temurin'
        java-version: '8'
        
    - name: Build with Maven
      run: mvn clean package  # Runs from repository root
    
    - name: Run Simulation
      run: |
        java -cp "src/cloudsim/simulations/target/classes:lib/*" \
          cloudsim.simulations.CostOptimizationSimulation

    # Optional: Cache Maven dependencies to speed up builds
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
