name: Cost Optimization CI

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        
    - name: Build with Maven
      run: |
        cd src/cloudsim/simulations
        mvn clean package
        
    - name: Run Simulation
      run: |
        cd src/cloudsim/simulations
        java -cp "target/classes:../../lib/*" cloudsim.simulations.CostOptimizationSimulation
